# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ArticlesReviewDate do
  @moduledoc """
  Date and time when all articles were reviewed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :dateReviewed
  ]

  @type t :: %__MODULE__{
    :dateReviewed => DateTime.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ArticlesReviewDate do
  def decode(value, _options) do
    value
  end
end

