# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.Assignee do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :userId,
    :note
  ]

  @type t :: %__MODULE__{
    :userId => String.t,
    :note => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.Assignee do
  def decode(value, _options) do
    value
  end
end

