# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.AuditEventSourceType do
  @moduledoc """
  Enumeration of available audit event sources types.  Possible types of audit event sources are:  * DESKTOP - Signifies the event is originating from DESKTOP/UI * DESKTOP_BULK - Signifies the event is originating from DESKTOP/UI Bulk actions * API - Signifies the event is originating from API * API_BULK - Signifies the event is originating from API Bulk actions * DESKTOP_BATCH - Signifies the event is originating from DESKTOP/UI Batch screening * API_BATCH - Signifies the event is originating from API Batch screening via saveAndScreen endpoint * OGS - Signifies the event is originating from ongoing screening * UNKNOWN - Signifies the event source is unknown 
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.AuditEventSourceType do
  def decode(value, _options) do
    value
  end
end

