# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.AuditSearchResponse do
  @moduledoc """
  Audit Search Response Object
  """

  @derive [Poison.Encoder]
  defstruct [
    :query,
    :sort,
    :pagination,
    :totalResultCount,
    :results
  ]

  @type t :: %__MODULE__{
    :query => String.t | nil,
    :sort => [RefinitivWorldCheckOneAPI.Model.SortCriterion.t] | nil,
    :pagination => RefinitivWorldCheckOneAPI.Model.PaginationResponse.t | nil,
    :totalResultCount => integer(),
    :results => [RefinitivWorldCheckOneAPI.Model.AuditEvent.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.AuditSearchResponse do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sort, :list, RefinitivWorldCheckOneAPI.Model.SortCriterion, options)
    |> deserialize(:pagination, :struct, RefinitivWorldCheckOneAPI.Model.PaginationResponse, options)
    |> deserialize(:results, :list, RefinitivWorldCheckOneAPI.Model.AuditEvent, options)
  end
end

