# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.BatchDetail do
  @moduledoc """
  Batch detail referenced from GenericCaseAuditDetails
  """

  @derive [Poison.Encoder]
  defstruct [
    :batchId,
    :batchName
  ]

  @type t :: %__MODULE__{
    :batchId => String.t,
    :batchName => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.BatchDetail do
  def decode(value, _options) do
    value
  end
end

