# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseBulkStatus do
  @moduledoc """
  Case Bulk Status
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseSystemId,
    :success,
    :errors
  ]

  @type t :: %__MODULE__{
    :caseSystemId => String.t,
    :success => boolean(),
    :errors => [RefinitivWorldCheckOneAPI.Model.Error.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseBulkStatus do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, RefinitivWorldCheckOneAPI.Model.Error, options)
  end
end

