# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseBulkArchiveRequest do
  @moduledoc """
  A request body on Bulk Update Archive States
  """

  @derive [Poison.Encoder]
  defstruct [
    :archive,
    :caseSystemIds,
    :note
  ]

  @type t :: %__MODULE__{
    :archive => boolean(),
    :caseSystemIds => [String.t],
    :note => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseBulkArchiveRequest do
  def decode(value, _options) do
    value
  end
end

