# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseScreeningRequest do
  @moduledoc """
  Defines Case Screening Request that could be sent for an existing Case.
  """

  @derive [Poison.Encoder]
  defstruct [
    :screeningMode,
    :caseInfo
  ]

  @type t :: %__MODULE__{
    :screeningMode => String.t | nil,
    :caseInfo => boolean() | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseScreeningRequest do
  def decode(value, _options) do
    value
  end
end

