# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseSearchUserSummary do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :fullName
  ]

  @type t :: %__MODULE__{
    :fullName => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseSearchUserSummary do
  def decode(value, _options) do
    value
  end
end

