# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseBulkLinkRequest do
  @moduledoc """
  Case Bulk Link Request
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseSystemId,
    :relatedCaseSystemIds
  ]

  @type t :: %__MODULE__{
    :caseSystemId => String.t,
    :relatedCaseSystemIds => [String.t]
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseBulkLinkRequest do
  def decode(value, _options) do
    value
  end
end

