# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseSummaryFilter do
  @moduledoc """
  Defines search criteria, sorting and items count in the response.
  """

  @derive [Poison.Encoder]
  defstruct [
    :query,
    :sort,
    :cursorOptions
  ]

  @type t :: %__MODULE__{
    :query => String.t | nil,
    :sort => [RefinitivWorldCheckOneAPI.Model.SortCriterion.t] | nil,
    :cursorOptions => RefinitivWorldCheckOneAPI.Model.CursorOptions.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseSummaryFilter do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sort, :list, RefinitivWorldCheckOneAPI.Model.SortCriterion, options)
    |> deserialize(:cursorOptions, :struct, RefinitivWorldCheckOneAPI.Model.CursorOptions, options)
  end
end

