# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseSystemId,
    :caseScreeningState,
    :lifecycleState,
    :assignee,
    :creator,
    :modifier,
    :creationDate,
    :modificationDate,
    :outstandingActions,
    :lastScreenedDatesByProviderType,
    :providerTypeDetails,
    :aggregatedResultSummaries
  ]

  @type t :: %__MODULE__{
    :caseSystemId => String.t | nil,
    :caseScreeningState => %{optional(String.t) => String.t} | nil,
    :lifecycleState => String.t | nil,
    :assignee => RefinitivWorldCheckOneAPI.Model.UserSummary.t | nil,
    :creator => RefinitivWorldCheckOneAPI.Model.UserSummary.t | nil,
    :modifier => RefinitivWorldCheckOneAPI.Model.UserSummary.t | nil,
    :creationDate => DateTime.t | nil,
    :modificationDate => DateTime.t | nil,
    :outstandingActions => boolean() | nil,
    :lastScreenedDatesByProviderType => %{optional(String.t) => DateTime.t} | nil,
    :providerTypeDetails => RefinitivWorldCheckOneAPI.Model.ProviderTypeDetails.t | nil,
    :aggregatedResultSummaries => RefinitivWorldCheckOneAPI.Model.CaseResultSummaries.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseAllOf do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:assignee, :struct, RefinitivWorldCheckOneAPI.Model.UserSummary, options)
    |> deserialize(:creator, :struct, RefinitivWorldCheckOneAPI.Model.UserSummary, options)
    |> deserialize(:modifier, :struct, RefinitivWorldCheckOneAPI.Model.UserSummary, options)
    |> deserialize(:providerTypeDetails, :struct, RefinitivWorldCheckOneAPI.Model.ProviderTypeDetails, options)
    |> deserialize(:aggregatedResultSummaries, :struct, RefinitivWorldCheckOneAPI.Model.CaseResultSummaries, options)
  end
end

