# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseRatingRequest do
  @moduledoc """
  The object representing a case rating.
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseRating,
    :reason
  ]

  @type t :: %__MODULE__{
    :caseRating => String.t,
    :reason => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseRatingRequest do
  def decode(value, _options) do
    value
  end
end

