# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseReference do
  @moduledoc """
  Container of 'caseId' and 'caseSystemId'.
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseSystemId,
    :caseId
  ]

  @type t :: %__MODULE__{
    :caseSystemId => String.t,
    :caseId => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseReference do
  def decode(value, _options) do
    value
  end
end

