# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CaseDetails do
  @moduledoc """
  Representation of a single case that is used for case creation operation. Defines Case data that can be sent when creating a new Case. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :caseId,
    :entityType,
    :name,
    :customFields,
    :secondaryFields
  ]

  @type t :: %__MODULE__{
    :caseId => String.t | nil,
    :entityType => String.t,
    :name => String.t,
    :customFields => [RefinitivWorldCheckOneAPI.Model.Field.t] | nil,
    :secondaryFields => [RefinitivWorldCheckOneAPI.Model.Field.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CaseDetails do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:customFields, :list, RefinitivWorldCheckOneAPI.Model.Field, options)
    |> deserialize(:secondaryFields, :list, RefinitivWorldCheckOneAPI.Model.Field, options)
  end
end

