# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ChangeCaseLifecycleStateAuditDetailsAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :previousCaseLifecycleState,
    :nextCaseLifecycleState
  ]

  @type t :: %__MODULE__{
    :previousCaseLifecycleState => String.t,
    :nextCaseLifecycleState => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ChangeCaseLifecycleStateAuditDetailsAllOf do
  def decode(value, _options) do
    value
  end
end

