# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ChangedCaseMediaCheckOgsPreferenceAuditDetailsAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :casePreferenceType,
    :status,
    :dateTimeModification
  ]

  @type t :: %__MODULE__{
    :casePreferenceType => RefinitivWorldCheckOneAPI.Model.CasePreferenceType.t,
    :status => String.t,
    :dateTimeModification => DateTime.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ChangedCaseMediaCheckOgsPreferenceAuditDetailsAllOf do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:casePreferenceType, :struct, RefinitivWorldCheckOneAPI.Model.CasePreferenceType, options)
  end
end

