# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ChangeCaseLifecycleStateAuditDetails do
  @moduledoc """
  Audit details for CHANGE_CASE_LIFECYCLE_STATE action raised when the Case Lifecycle state has changed. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType,
    :previousCaseLifecycleState,
    :nextCaseLifecycleState
  ]

  @type t :: %__MODULE__{
    :detailsType => String.t,
    :previousCaseLifecycleState => String.t,
    :nextCaseLifecycleState => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ChangeCaseLifecycleStateAuditDetails do
  def decode(value, _options) do
    value
  end
end

