# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ChildCaseTransferredInParent do
  @moduledoc """
  Audit details which contains information about a child case. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType,
    :childCaseExternalId,
    :fromParentCaseExternalId
  ]

  @type t :: %__MODULE__{
    :detailsType => String.t,
    :childCaseExternalId => String.t,
    :fromParentCaseExternalId => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ChildCaseTransferredInParent do
  def decode(value, _options) do
    value
  end
end

