# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ChildCaseTransferredOutParent do
  @moduledoc """
  Audit details contain information about a child case. For example, an audit event when a user moves a child case from/to one parent to another. Extends [AbstractAuditDetails](#AbstractAuditDetails). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType,
    :childCaseExternalId,
    :toParentCaseExternalId
  ]

  @type t :: %__MODULE__{
    :detailsType => String.t,
    :childCaseExternalId => String.t,
    :toParentCaseExternalId => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ChildCaseTransferredOutParent do
  def decode(value, _options) do
    value
  end
end

