# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.CountryLink do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :country,
    :countryText,
    :type
  ]

  @type t :: %__MODULE__{
    :country => RefinitivWorldCheckOneAPI.Model.Country.t,
    :countryText => String.t | nil,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.CountryLink do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:country, :struct, RefinitivWorldCheckOneAPI.Model.Country, options)
  end
end

