# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.EntitySupersede do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :entityId,
    :supersedingEntityId
  ]

  @type t :: %__MODULE__{
    :entityId => String.t,
    :supersedingEntityId => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.EntitySupersede do
  def decode(value, _options) do
    value
  end
end

