# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.EntityPurge do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :entityId,
    :purgedDate
  ]

  @type t :: %__MODULE__{
    :entityId => String.t,
    :purgedDate => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.EntityPurge do
  def decode(value, _options) do
    value
  end
end

