# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.EntityUpdatedDates do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ageUpdated,
    :aliasesUpdated,
    :alternativeSpellingUpdated,
    :asOfDateUpdated,
    :categoryUpdated,
    :citizenshipsUpdated,
    :companiesUpdated,
    :deceasedUpdated,
    :dobsUpdated,
    :eiUpdated,
    :enteredUpdated,
    :externalSourcesUpdated,
    :firstNameUpdated,
    :foreignAliasUpdated,
    :furtherInformationUpdated,
    :idNumbersUpdated,
    :keywordsUpdated,
    :lastNameUpdated,
    :linkedToUpdated,
    :locationsUpdated,
    :lowQualityAliasesUpdated,
    :passportsUpdated,
    :placeOfBirthUpdated,
    :positionUpdated,
    :ssnUpdated,
    :subCategoryUpdated,
    :titleUpdated,
    :updatecategoryUpdated,
    :sicUpdated
  ]

  @type t :: %__MODULE__{
    :ageUpdated => DateTime.t | nil,
    :aliasesUpdated => DateTime.t | nil,
    :alternativeSpellingUpdated => DateTime.t | nil,
    :asOfDateUpdated => DateTime.t | nil,
    :categoryUpdated => DateTime.t | nil,
    :citizenshipsUpdated => DateTime.t | nil,
    :companiesUpdated => DateTime.t | nil,
    :deceasedUpdated => DateTime.t | nil,
    :dobsUpdated => DateTime.t | nil,
    :eiUpdated => DateTime.t | nil,
    :enteredUpdated => DateTime.t | nil,
    :externalSourcesUpdated => DateTime.t | nil,
    :firstNameUpdated => DateTime.t | nil,
    :foreignAliasUpdated => DateTime.t | nil,
    :furtherInformationUpdated => DateTime.t | nil,
    :idNumbersUpdated => DateTime.t | nil,
    :keywordsUpdated => DateTime.t | nil,
    :lastNameUpdated => DateTime.t | nil,
    :linkedToUpdated => DateTime.t | nil,
    :locationsUpdated => DateTime.t | nil,
    :lowQualityAliasesUpdated => DateTime.t | nil,
    :passportsUpdated => DateTime.t | nil,
    :placeOfBirthUpdated => DateTime.t | nil,
    :positionUpdated => DateTime.t | nil,
    :ssnUpdated => DateTime.t | nil,
    :subCategoryUpdated => DateTime.t | nil,
    :titleUpdated => DateTime.t | nil,
    :updatecategoryUpdated => DateTime.t | nil,
    :sicUpdated => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.EntityUpdatedDates do
  def decode(value, _options) do
    value
  end
end

