# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.Event do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :address,
    :allegedAddresses,
    :day,
    :fullDate,
    :month,
    :type,
    :year
  ]

  @type t :: %__MODULE__{
    :address => RefinitivWorldCheckOneAPI.Model.Address.t | nil,
    :allegedAddresses => [RefinitivWorldCheckOneAPI.Model.Address.t] | nil,
    :day => integer() | nil,
    :fullDate => String.t | nil,
    :month => integer() | nil,
    :type => RefinitivWorldCheckOneAPI.Model.EventType.t,
    :year => integer() | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.Event do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:address, :struct, RefinitivWorldCheckOneAPI.Model.Address, options)
    |> deserialize(:allegedAddresses, :list, RefinitivWorldCheckOneAPI.Model.Address, options)
    |> deserialize(:type, :struct, RefinitivWorldCheckOneAPI.Model.EventType, options)
  end
end

