# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.FieldDefinition do
  @moduledoc """
  Secondary or Custom Field metadata describing the rules for populating the corresponding Field data when creating or updating a Case. Extends [AbstractField](#AbstractField). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :typeId,
    :fieldValueType,
    :fieldRequired,
    :label,
    :regExp
  ]

  @type t :: %__MODULE__{
    :typeId => String.t,
    :fieldValueType => RefinitivWorldCheckOneAPI.Model.FieldValueType.t,
    :fieldRequired => boolean() | nil,
    :label => String.t,
    :regExp => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.FieldDefinition do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fieldValueType, :struct, RefinitivWorldCheckOneAPI.Model.FieldValueType, options)
  end
end

