# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.FieldAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :value,
    :dateTimeValue
  ]

  @type t :: %__MODULE__{
    :value => String.t | nil,
    :dateTimeValue => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.FieldAllOf do
  def decode(value, _options) do
    value
  end
end

