# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.FieldValueType do
  @moduledoc """
  Enumerated value formats for a secondary / custom field.  - GENDER can be one of enumerated values in `GenderType.UKNOWN/MALE/FEMALE`. - DATE is a Date in ISO 8601 format excluding Week and Ordinal dates. - COUNTRY is a ISO_3166-1_alpha-3 Country Code. All supported country codes can be obtained via `/reference/countries`. - PASSPORT_DOCUMENT_TYPE can be screened by `ProviderType.PASSPORT_CHECK`. - STATE - a State/Country type used by `ProviderType.PASSPORT_CHECK` for nationality and passport issuing state. - TEXT is a string. 
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.FieldValueType do
  def decode(value, _options) do
    value
  end
end

