# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.FileMeta do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :caption,
    :uri,
    :tags
  ]

  @type t :: %__MODULE__{
    :caption => String.t,
    :uri => String.t,
    :tags => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.FileMeta do
  def decode(value, _options) do
    value
  end
end

