# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.Filter do
  @moduledoc """
  Filter the response
  """

  @derive [Poison.Encoder]
  defstruct [
    :query,
    :sort,
    :pagination
  ]

  @type t :: %__MODULE__{
    :query => String.t | nil,
    :sort => [RefinitivWorldCheckOneAPI.Model.SortCriterion.t] | nil,
    :pagination => RefinitivWorldCheckOneAPI.Model.Pagination.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.Filter do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sort, :list, RefinitivWorldCheckOneAPI.Model.SortCriterion, options)
    |> deserialize(:pagination, :struct, RefinitivWorldCheckOneAPI.Model.Pagination, options)
  end
end

