# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.IdentityDocumentLocationTypeDataSet do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :identityDocumentLocationTypes
  ]

  @type t :: %__MODULE__{
    :identityDocumentLocationTypes => [RefinitivWorldCheckOneAPI.Model.IdentityDocumentLocationType.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.IdentityDocumentLocationTypeDataSet do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identityDocumentLocationTypes, :list, RefinitivWorldCheckOneAPI.Model.IdentityDocumentLocationType, options)
  end
end

