# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.IdentityDocumentLocationType do
  @moduledoc """
  Represents the type of identity document location that includes the type of document, name, country, and what type of entity it belongs to. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :country,
    :name,
    :type,
    :entityTypes
  ]

  @type t :: %__MODULE__{
    :country => RefinitivWorldCheckOneAPI.Model.Country.t | nil,
    :name => String.t | nil,
    :type => String.t | nil,
    :entityTypes => [RefinitivWorldCheckOneAPI.Model.EntityType.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.IdentityDocumentLocationType do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:country, :struct, RefinitivWorldCheckOneAPI.Model.Country, options)
    |> deserialize(:entityTypes, :list, RefinitivWorldCheckOneAPI.Model.EntityType, options)
  end
end

