# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.IdentityDocument do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :entity,
    :expiryDate,
    :issueDate,
    :issuer,
    :locationType,
    :number,
    :type
  ]

  @type t :: %__MODULE__{
    :entity => RefinitivWorldCheckOneAPI.Model.Entity.t | nil,
    :expiryDate => String.t | nil,
    :issueDate => String.t | nil,
    :issuer => String.t | nil,
    :locationType => RefinitivWorldCheckOneAPI.Model.IdentityDocumentLocationType.t | nil,
    :number => String.t | nil,
    :type => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.IdentityDocument do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:entity, :struct, RefinitivWorldCheckOneAPI.Model.Entity, options)
    |> deserialize(:locationType, :struct, RefinitivWorldCheckOneAPI.Model.IdentityDocumentLocationType, options)
  end
end

