# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.Image do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :caption,
    :height,
    :imageUseCode,
    :uri,
    :tags,
    :width
  ]

  @type t :: %__MODULE__{
    :caption => String.t | nil,
    :height => integer() | nil,
    :imageUseCode => String.t | nil,
    :uri => String.t,
    :tags => [String.t] | nil,
    :width => integer() | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.Image do
  def decode(value, _options) do
    value
  end
end

