# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.IndividualEntityAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :age,
    :ageAsOfDate,
    :events,
    :gender,
    :isDeceased,
    :previousRoles,
    :roles,
    :entityType
  ]

  @type t :: %__MODULE__{
    :age => String.t | nil,
    :ageAsOfDate => DateTime.t | nil,
    :events => [RefinitivWorldCheckOneAPI.Model.Event.t] | nil,
    :gender => RefinitivWorldCheckOneAPI.Model.Gender.t | nil,
    :isDeceased => boolean() | nil,
    :previousRoles => [RefinitivWorldCheckOneAPI.Model.Role.t] | nil,
    :roles => [RefinitivWorldCheckOneAPI.Model.Role.t] | nil,
    :entityType => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.IndividualEntityAllOf do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:events, :list, RefinitivWorldCheckOneAPI.Model.Event, options)
    |> deserialize(:gender, :struct, RefinitivWorldCheckOneAPI.Model.Gender, options)
    |> deserialize(:previousRoles, :list, RefinitivWorldCheckOneAPI.Model.Role, options)
    |> deserialize(:roles, :list, RefinitivWorldCheckOneAPI.Model.Role, options)
  end
end

