# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.IndividualAssociate do
  @moduledoc """
  Associate entity details. Represents Individual entity. Extends [AbstractAssociate](#AbstractAssociate). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :associateEntityType,
    :entityType,
    :reversed,
    :targetEntityId,
    :targetExternalImportId,
    :type,
    :targetPrimaryName,
    :creationDate,
    :modificationDate,
    :updateCategory,
    :category,
    :targetCategories,
    :age,
    :ageAsOfDate,
    :targetDOBs
  ]

  @type t :: %__MODULE__{
    :associateEntityType => String.t,
    :entityType => String.t,
    :reversed => boolean() | nil,
    :targetEntityId => String.t | nil,
    :targetExternalImportId => String.t | nil,
    :type => String.t | nil,
    :targetPrimaryName => String.t | nil,
    :creationDate => DateTime.t | nil,
    :modificationDate => DateTime.t | nil,
    :updateCategory => String.t | nil,
    :category => String.t | nil,
    :targetCategories => [String.t] | nil,
    :age => String.t | nil,
    :ageAsOfDate => DateTime.t | nil,
    :targetDOBs => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.IndividualAssociate do
  def decode(value, _options) do
    value
  end
end

