# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MatchedTerm do
  @moduledoc """
  Matched term of a Result.
  """

  @derive [Poison.Encoder]
  defstruct [
    :term,
    :type
  ]

  @type t :: %__MODULE__{
    :term => String.t | nil,
    :type => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MatchedTerm do
  def decode(value, _options) do
    value
  end
end

