# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MediaCheckRegularFacetResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :drilldownKey,
    :facetLabel,
    :articleCount
  ]

  @type t :: %__MODULE__{
    :drilldownKey => String.t | nil,
    :facetLabel => String.t | nil,
    :articleCount => integer() | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MediaCheckRegularFacetResponse do
  def decode(value, _options) do
    value
  end
end

