# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MediaCheckCaseDetails do
  @moduledoc """
  Details about the Media-Check settings on a case (e.g., smart filter).
  """

  @derive [Poison.Encoder]
  defstruct [
    :smartFilter
  ]

  @type t :: %__MODULE__{
    :smartFilter => boolean()
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MediaCheckCaseDetails do
  def decode(value, _options) do
    value
  end
end

