# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MediaCheckArticleSummary do
  @moduledoc """
  MediaCheck news article summary 
  """

  @derive [Poison.Encoder]
  defstruct [
    :articleId,
    :articleFound,
    :author,
    :contentType,
    :countries,
    :duplicatesKey,
    :language,
    :publicationDate,
    :snippet,
    :publication,
    :title,
    :topics,
    :wordCount,
    :phases
  ]

  @type t :: %__MODULE__{
    :articleId => String.t | nil,
    :articleFound => boolean() | nil,
    :author => String.t | nil,
    :contentType => String.t | nil,
    :countries => [String.t] | nil,
    :duplicatesKey => String.t | nil,
    :language => String.t | nil,
    :publicationDate => DateTime.t | nil,
    :snippet => String.t | nil,
    :publication => RefinitivWorldCheckOneAPI.Model.MediaCheckPublicationDetails.t | nil,
    :title => String.t | nil,
    :topics => [String.t] | nil,
    :wordCount => integer() | nil,
    :phases => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MediaCheckArticleSummary do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:publication, :struct, RefinitivWorldCheckOneAPI.Model.MediaCheckPublicationDetails, options)
  end
end

