# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MediaCheckDetachArticlesRequest do
  @moduledoc """
  Articles to detach.
  """

  @derive [Poison.Encoder]
  defstruct [
    :articleIds
  ]

  @type t :: %__MODULE__{
    :articleIds => [String.t]
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MediaCheckDetachArticlesRequest do
  def decode(value, _options) do
    value
  end
end

