# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MediaCheckPublicationDateRange do
  @moduledoc """
  Date range when the article was published.
  """

  @derive [Poison.Encoder]
  defstruct [
    :min,
    :max
  ]

  @type t :: %__MODULE__{
    :min => DateTime.t | nil,
    :max => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MediaCheckPublicationDateRange do
  def decode(value, _options) do
    value
  end
end

