# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MediaCheckDuplicatesRequest do
  @moduledoc """
  Request containing deduplication hash to retrieve article duplicatates.
  """

  @derive [Poison.Encoder]
  defstruct [
    :deduplicationHash
  ]

  @type t :: %__MODULE__{
    :deduplicationHash => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MediaCheckDuplicatesRequest do
  def decode(value, _options) do
    value
  end
end

