# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MergeCaseAuditDetailsAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :childCaseId,
    :childCaseExternalId,
    :childCaseName,
    :childCaseCreatedDate
  ]

  @type t :: %__MODULE__{
    :childCaseId => String.t,
    :childCaseExternalId => String.t,
    :childCaseName => String.t,
    :childCaseCreatedDate => DateTime.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MergeCaseAuditDetailsAllOf do
  def decode(value, _options) do
    value
  end
end

