# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MrzGenerationResponse do
  @moduledoc """
  PassportCheck Machine Readable Zone (MRZ) data response 
  """

  @derive [Poison.Encoder]
  defstruct [
    :lines,
    :isConformICAO
  ]

  @type t :: %__MODULE__{
    :lines => [String.t] | nil,
    :isConformICAO => boolean() | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MrzGenerationResponse do
  def decode(value, _options) do
    value
  end
end

