# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.MrzGenerationRequest do
  @moduledoc """
  PassportCheck Machine Readable Zone (MRZ) data request 
  """

  @derive [Poison.Encoder]
  defstruct [
    :givenName,
    :lastName,
    :gender,
    :dateOfBirth,
    :issuingState,
    :nationality,
    :identificationNumber,
    :dateOfExpiry,
    :documentType
  ]

  @type t :: %__MODULE__{
    :givenName => String.t,
    :lastName => String.t,
    :gender => String.t,
    :dateOfBirth => Date.t,
    :issuingState => String.t,
    :nationality => String.t,
    :identificationNumber => String.t,
    :dateOfExpiry => Date.t,
    :documentType => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.MrzGenerationRequest do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:dateOfBirth, :date, nil, options)
    |> deserialize(:dateOfExpiry, :date, nil, options)
  end
end

