# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.Name do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :fullName,
    :givenName,
    :languageCode,
    :lastName,
    :originalScript,
    :prefix,
    :suffix,
    :type
  ]

  @type t :: %__MODULE__{
    :fullName => String.t,
    :givenName => String.t | nil,
    :languageCode => RefinitivWorldCheckOneAPI.Model.LanguageCode.t | nil,
    :lastName => String.t | nil,
    :originalScript => String.t | nil,
    :prefix => String.t | nil,
    :suffix => String.t | nil,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.Name do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:languageCode, :struct, RefinitivWorldCheckOneAPI.Model.LanguageCode, options)
  end
end

