# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.OngoingScreeningRequest do
  @moduledoc """
  Request containing ongoing screening details
  """

  @derive [Poison.Encoder]
  defstruct [
    :providerTypes,
    :note
  ]

  @type t :: %__MODULE__{
    :providerTypes => [RefinitivWorldCheckOneAPI.Model.OngoingScreeningProviderType.t] | nil,
    :note => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.OngoingScreeningRequest do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:providerTypes, :list, RefinitivWorldCheckOneAPI.Model.OngoingScreeningProviderType, options)
  end
end

