# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.OrganisationSecondaryFields do
  @moduledoc """
  Secondary fields defined for entity type organisation and it is referenced from EDDRequestAuditDetails
  """

  @derive [Poison.Encoder]
  defstruct [
    :registeredCountry
  ]

  @type t :: %__MODULE__{
    :registeredCountry => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.OrganisationSecondaryFields do
  def decode(value, _options) do
    value
  end
end

