# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ParentCaseDetailsChangedEventDetails do
  @moduledoc """
  Audit details which contains information about a change to the parent case. Extends [AbstractAuditDetails](#AbstractAuditDetails).
  """

  @derive [Poison.Encoder]
  defstruct [
    :detailsType,
    :externalId,
    :caseName,
    :previousExternalId,
    :previousCaseName
  ]

  @type t :: %__MODULE__{
    :detailsType => String.t,
    :externalId => String.t,
    :caseName => String.t,
    :previousExternalId => String.t,
    :previousCaseName => String.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ParentCaseDetailsChangedEventDetails do
  def decode(value, _options) do
    value
  end
end

