# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.PepDetailsRequest do
  @moduledoc """
  A request containing defined the sort order for retrieved PEP roles details.
  """

  @derive [Poison.Encoder]
  defstruct [
    :sort
  ]

  @type t :: %__MODULE__{
    :sort => RefinitivWorldCheckOneAPI.Model.SortCriterion.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.PepDetailsRequest do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sort, :struct, RefinitivWorldCheckOneAPI.Model.SortCriterion, options)
  end
end

