# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.PepDetailsResponse do
  @moduledoc """
  Retrieves detailed information for \"Politically Exposed Person (PEP)\" category by given record ID.
  """

  @derive [Poison.Encoder]
  defstruct [
    :sort,
    :pepStatus,
    :updatedDates,
    :roleDetails
  ]

  @type t :: %__MODULE__{
    :sort => RefinitivWorldCheckOneAPI.Model.SortCriterion.t | nil,
    :pepStatus => String.t | nil,
    :updatedDates => RefinitivWorldCheckOneAPI.Model.PepUpdatedDates.t | nil,
    :roleDetails => [RefinitivWorldCheckOneAPI.Model.RoleDetails.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.PepDetailsResponse do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sort, :struct, RefinitivWorldCheckOneAPI.Model.SortCriterion, options)
    |> deserialize(:updatedDates, :struct, RefinitivWorldCheckOneAPI.Model.PepUpdatedDates, options)
    |> deserialize(:roleDetails, :list, RefinitivWorldCheckOneAPI.Model.RoleDetails, options)
  end
end

