# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ProfileEntityType do
  @moduledoc """
  Profile Entity Type Enumeration.  The `Entity` subclasses corresponding to each type of entity are:  * `COUNTRY` : `CountryEntity` * `INDIVIDUAL` : `IndividualEntity` * `ORGANISATION` : `OrganisationEntity` * `VESSEL` : `VesselEntity` 
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ProfileEntityType do
  def decode(value, _options) do
    value
  end
end

