# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.Provider do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :identifier,
    :master,
    :name
  ]

  @type t :: %__MODULE__{
    :code => String.t | nil,
    :identifier => String.t | nil,
    :master => boolean() | nil,
    :name => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.Provider do
  def decode(value, _options) do
    value
  end
end

