# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ProviderDetailAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :sources
  ]

  @type t :: %__MODULE__{
    :sources => [RefinitivWorldCheckOneAPI.Model.ProviderSource.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ProviderDetailAllOf do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sources, :list, RefinitivWorldCheckOneAPI.Model.ProviderSource, options)
  end
end

