# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ProviderTypeDetails do
  @moduledoc """
  Details about the specific provider type.
  """

  @derive [Poison.Encoder]
  defstruct [
    :mediaCheck
  ]

  @type t :: %__MODULE__{
    :mediaCheck => RefinitivWorldCheckOneAPI.Model.MediaCheckCaseDetails.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ProviderTypeDetails do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:mediaCheck, :struct, RefinitivWorldCheckOneAPI.Model.MediaCheckCaseDetails, options)
  end
end

