# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ProviderSource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :abbreviation,
    :creationDate,
    :identifier,
    :importIdentifier,
    :name,
    :provider,
    :providerSourceStatus,
    :regionOfAuthority,
    :subscriptionCategory,
    :type
  ]

  @type t :: %__MODULE__{
    :abbreviation => String.t,
    :creationDate => DateTime.t | nil,
    :identifier => String.t,
    :importIdentifier => String.t | nil,
    :name => String.t,
    :provider => RefinitivWorldCheckOneAPI.Model.Provider.t | nil,
    :providerSourceStatus => String.t,
    :regionOfAuthority => String.t | nil,
    :subscriptionCategory => String.t | nil,
    :type => RefinitivWorldCheckOneAPI.Model.ProviderSourceType.t
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ProviderSource do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:provider, :struct, RefinitivWorldCheckOneAPI.Model.Provider, options)
    |> deserialize(:type, :struct, RefinitivWorldCheckOneAPI.Model.ProviderSourceType, options)
  end
end

