# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ProviderDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :identifier,
    :master,
    :name,
    :sources
  ]

  @type t :: %__MODULE__{
    :code => String.t | nil,
    :identifier => String.t | nil,
    :master => boolean() | nil,
    :name => String.t | nil,
    :sources => [RefinitivWorldCheckOneAPI.Model.ProviderSource.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ProviderDetail do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sources, :list, RefinitivWorldCheckOneAPI.Model.ProviderSource, options)
  end
end

