# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ProviderSourceType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :category,
    :identifier,
    :name
  ]

  @type t :: %__MODULE__{
    :category => RefinitivWorldCheckOneAPI.Model.ProviderSourceTypeCategoryDetail.t | nil,
    :identifier => String.t | nil,
    :name => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ProviderSourceType do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:category, :struct, RefinitivWorldCheckOneAPI.Model.ProviderSourceTypeCategoryDetail, options)
  end
end

