# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ResolutionField do
  @moduledoc """
  Represents the ID, label and type for a Status, a Risk or a Reason.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :label,
    :type
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :label => String.t,
    :type => RefinitivWorldCheckOneAPI.Model.ResolutionStatusType.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ResolutionField do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, RefinitivWorldCheckOneAPI.Model.ResolutionStatusType, options)
  end
end

