# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ResolutionFields do
  @moduledoc """
  Describes all resolution fields (statuses, risks and reasons) in detail.
  """

  @derive [Poison.Encoder]
  defstruct [
    :statuses,
    :risks,
    :reasons
  ]

  @type t :: %__MODULE__{
    :statuses => [RefinitivWorldCheckOneAPI.Model.ResolutionField.t],
    :risks => [RefinitivWorldCheckOneAPI.Model.ResolutionField.t],
    :reasons => [RefinitivWorldCheckOneAPI.Model.ResolutionField.t]
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ResolutionFields do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:statuses, :list, RefinitivWorldCheckOneAPI.Model.ResolutionField, options)
    |> deserialize(:risks, :list, RefinitivWorldCheckOneAPI.Model.ResolutionField, options)
    |> deserialize(:reasons, :list, RefinitivWorldCheckOneAPI.Model.ResolutionField, options)
  end
end

