# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ResolutionAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :resolutionDate
  ]

  @type t :: %__MODULE__{
    :resolutionDate => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ResolutionAllOf do
  def decode(value, _options) do
    value
  end
end

