# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.Review do
  @moduledoc """
  Review details of a Result.
  """

  @derive [Poison.Encoder]
  defstruct [
    :reviewRequired,
    :reviewRequiredDate,
    :reviewRemark,
    :reviewDate
  ]

  @type t :: %__MODULE__{
    :reviewRequired => boolean() | nil,
    :reviewRequiredDate => DateTime.t | nil,
    :reviewRemark => String.t | nil,
    :reviewDate => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.Review do
  def decode(value, _options) do
    value
  end
end

