# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.Role do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :end,
    :location,
    :source,
    :start,
    :title,
    :type
  ]

  @type t :: %__MODULE__{
    :end => String.t | nil,
    :location => String.t | nil,
    :source => RefinitivWorldCheckOneAPI.Model.ProviderSource.t | nil,
    :start => String.t | nil,
    :title => String.t | nil,
    :type => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.Role do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:source, :struct, RefinitivWorldCheckOneAPI.Model.ProviderSource, options)
  end
end

