# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.ScreeningStatusRequestCollection do
  @moduledoc """
  Collection  of 'ScreeningStatusRequest'. The maximum number of cases is configured in account settings. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :screeningStatusRequests,
    :providerTypes
  ]

  @type t :: %__MODULE__{
    :screeningStatusRequests => [RefinitivWorldCheckOneAPI.Model.ScreeningStatusRequest.t] | nil,
    :providerTypes => [RefinitivWorldCheckOneAPI.Model.ProviderType.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.ScreeningStatusRequestCollection do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:screeningStatusRequests, :list, RefinitivWorldCheckOneAPI.Model.ScreeningStatusRequest, options)
    |> deserialize(:providerTypes, :list, RefinitivWorldCheckOneAPI.Model.ProviderType, options)
  end
end

