# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.SearchResponse do
  @moduledoc """
  Common fields used in search responses.  These fields are included in response types, and objects of this type are not returned directly.
  """

  @derive [Poison.Encoder]
  defstruct [
    :query,
    :sort,
    :pagination,
    :totalResultCount
  ]

  @type t :: %__MODULE__{
    :query => String.t | nil,
    :sort => [RefinitivWorldCheckOneAPI.Model.SortCriterion.t] | nil,
    :pagination => RefinitivWorldCheckOneAPI.Model.PaginationResponse.t | nil,
    :totalResultCount => integer()
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.SearchResponse do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sort, :list, RefinitivWorldCheckOneAPI.Model.SortCriterion, options)
    |> deserialize(:pagination, :struct, RefinitivWorldCheckOneAPI.Model.PaginationResponse, options)
  end
end

