# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.SecondaryFieldsByEntity do
  @moduledoc """
  Wrapper which contains secondary fields grouped by CaseEntityType.
  """

  @derive [Poison.Encoder]
  defstruct [
    :secondaryFieldsByEntity
  ]

  @type t :: %__MODULE__{
    :secondaryFieldsByEntity => %{optional(String.t) => [RefinitivWorldCheckOneAPI.Model.FieldDefinition.t]}
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.SecondaryFieldsByEntity do
  def decode(value, _options) do
    value
  end
end

