# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.SmartFilterResponse do
  @moduledoc """
  Retrieved smart filter state on a Case. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :smartFilter
  ]

  @type t :: %__MODULE__{
    :smartFilter => boolean() | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.SmartFilterResponse do
  def decode(value, _options) do
    value
  end
end

