# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.SortCriterion do
  @moduledoc """
  Sort specification
  """

  @derive [Poison.Encoder]
  defstruct [
    :columnName,
    :order
  ]

  @type t :: %__MODULE__{
    :columnName => String.t | nil,
    :order => String.t | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.SortCriterion do
  def decode(value, _options) do
    value
  end
end

