# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.StatedGender do
  @moduledoc """
  Stated gender Type Enumeration
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.StatedGender do
  def decode(value, _options) do
    value
  end
end

