# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RefinitivWorldCheckOneAPI.Model.WatchlistDataSet do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :entityCreateOrUpdate,
    :entityDelete,
    :entitySupersede,
    :entityPurge
  ]

  @type t :: %__MODULE__{
    :entityCreateOrUpdate => [RefinitivWorldCheckOneAPI.Model.Entity.t] | nil,
    :entityDelete => [RefinitivWorldCheckOneAPI.Model.EntityDelete.t] | nil,
    :entitySupersede => [RefinitivWorldCheckOneAPI.Model.EntitySupersede.t] | nil,
    :entityPurge => [RefinitivWorldCheckOneAPI.Model.EntityPurge.t] | nil
  }
end

defimpl Poison.Decoder, for: RefinitivWorldCheckOneAPI.Model.WatchlistDataSet do
  import RefinitivWorldCheckOneAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:entityCreateOrUpdate, :list, RefinitivWorldCheckOneAPI.Model.Entity, options)
    |> deserialize(:entityDelete, :list, RefinitivWorldCheckOneAPI.Model.EntityDelete, options)
    |> deserialize(:entitySupersede, :list, RefinitivWorldCheckOneAPI.Model.EntitySupersede, options)
    |> deserialize(:entityPurge, :list, RefinitivWorldCheckOneAPI.Model.EntityPurge, options)
  end
end

